#!/usr/bin/env python3
"""scripts/cache/kai_menu.json (scraped from kaicoffeeco.com's bundle) → js/data.js.

Nothing here is invented. Categories, items, prices, ingredients, badges and the
hidden flag are the client's; so are the branches, their Persian addresses, the
Google Maps links and the loyalty leagues. What the app adds — the points rule,
the demo roster — lives in js/config.js and is labelled as preview.

    python3 scripts/build_data.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
raw = json.loads((ROOT / "scripts" / "cache" / "kai_menu.json").read_text(encoding="utf-8"))

ICON = {  # our own glyph per category (see js/icons.js)
    "espresso-drinks": "cup", "warm-drinks": "steam", "cold-coffee": "ice",
    "cold-drinks": "straw", "refreshers": "leaf", "breakfast": "egg",
    "snacks": "toast", "bakery": "croissant", "combo": "combo",
}
CAT_EN = {  # their English category labels, as on the site
    c["id"]: c["nameEn"] for c in raw["categories"]
}

categories = [{"id": c["id"], "en": c["nameEn"], "fa": c["nameFa"], "icon": ICON[c["id"]]}
              for c in raw["categories"]]

items = []
for it in raw["items"]:
    if it.get("isHidden") or it.get("isVisible") is False:
        continue                     # hidden on their site (seasonal) — hidden here
    en = it["titleEn"]
    size = None
    m = re.match(r"^(.*?)\s+(Medium)$", en)
    if m:
        en, size = m.group(1), m.group(2)
    badge = {"تازه‌های کای": "new", "فصلی": "seasonal"}.get(it.get("badgeFa"))
    items.append({
        "id": it["id"], "cat": it["categoryId"], "en": en, "fa": it["titleFa"],
        "price": it["priceToman"], "ing": it.get("ingredientsFa", ""),
        "ingEn": it.get("previewDescriptionEn"), "size": size, "badge": badge,
        "img": f"assets/items/{it['id']}.webp",
    })

BRANCH_ADDR = {  # from the bundle: the detailed Persian addresses
    "vanak": "خیابان خدامی- رو به روی هتل هما- کوچه شادی ۲",
    "shahrak-gharb": "شهرک غرب- سیمای ایران- رو به روی بیمارستان لاله- ساختمان لاله",
    "jordan": "خیابان نلسون ماندلا- بین کوچه سلطانی و کوچه انصاری",
    "pasdaran": "پاسداران- خیابان پایدارفرد- نبش بوستان هشتم",
    "velenjak": "ولنجک- خ سیزدهم- نبش خیابان ساسان- ساختمان هیترا",
    "mirdamad": "میرداماد- میدان مادر به سمتِ شریعتی- لاینِ کندرو- پلاک ۵۴",
    "kish": "جزیره کیش",
    "royan": "وازیوار- رو به روی شهرکِ گلستانک",
}
BRANCHES = [  # order as on kaicoffeeco.com/branches
    ("velenjak", "ولنجک", "Velenjak", "Tehran", "https://maps.app.goo.gl/qY52D3wF5dmRqemg8", "open"),
    ("royan", "رویان", "Royan", "Mazandaran", "https://maps.app.goo.gl/TVG2Q1UmCYCpy4S79", "open"),
    ("vanak", "ونک", "Vanak", "Tehran", "https://maps.app.goo.gl/kikFATpV3mGFrHoWA", "open"),
    ("shahrak-gharb", "شهرک غرب", "Shahrak-e Gharb", "Tehran", "https://maps.app.goo.gl/VxnCkdksdATDxZFm9", "open"),
    ("jordan", "جردن", "Jordan", "Tehran", "https://maps.app.goo.gl/vcYuQ6qCJR9cq5sc7", "open"),
    ("pasdaran", "پاسداران", "Pasdaran", "Tehran", "https://maps.app.goo.gl/yuC9GX3rzUwdcxB38", "open"),
    ("mirdamad", "میرداماد", "Mirdamad", "Tehran", "https://maps.app.goo.gl/LQt1kPH5x9hXa3vTA", "open"),
    ("kish", "کیش", "Kish", "Kish Island", None, "soon"),
]
branches = [{
    "id": slug, "fa": fa, "en": en, "region": region, "address": BRANCH_ADDR[slug],
    "maps": maps, "status": status, "img": f"assets/branches/{slug}.webp",
    "ownMenu": slug == "royan",
} for slug, fa, en, region, maps, status in BRANCHES]

leagues = [  # kaicoffeeco.com/kai-loyalty-program — five leagues, cashback 7 → 22 %
    {"id": "stranger", "en": "Stranger", "fa": "ناآشنا", "cashback": 7, "min": 0,
     "fa_line": "از اولین خرید عضو می‌شوید و همان ابتدا ۷٪ کش‌بک می‌گیرید."},
    {"id": "friend", "en": "Friend", "fa": "دوست", "cashback": 12, "min": 5000,
     "fa_line": "با رسیدن به ۵٬۰۰۰ امتیاز، لیگ دوست باز می‌شود و کش‌بک شما به ۱۲٪ می‌رسد."},
    {"id": "close-friend", "en": "Close Friend", "fa": "دوست نزدیک", "cashback": 15, "min": 10000,
     "fa_line": "با ۱۰٬۰۰۰ امتیاز وارد لیگ دوست نزدیک می‌شوید و ۱۵٪ کش‌بک دریافت می‌کنید."},
    {"id": "best-friend", "en": "Best Friend", "fa": "بهترین دوست", "cashback": 17, "min": 20000,
     "fa_line": "با ۲۰٬۰۰۰ امتیاز به لیگ بهترین دوست می‌رسید؛ ۱۷٪ کش‌بک و حس تعلق بیشتر به جامعه کای."},
    {"id": "legend", "en": "Legend", "fa": "افسانه‌ای", "cashback": 22, "min": 50000,
     "fa_line": "با ۵۰٬۰۰۰ امتیاز به لیگ افسانه‌ای می‌رسید؛ بالاترین کش‌بک ۲۲٪ و تجربه ویژه اعضای وفادار."},
]

def js(name, value):
    return f"export const {name} = {json.dumps(value, ensure_ascii=False, indent=1)};\n\n"

out = ("// Generated by scripts/build_data.py from scripts/cache/kai_menu.json.\n"
       "// Everything in this file is KAI's own: kaicoffeeco.com, fetched 2026-09-11.\n"
       "// Edit the source and rebuild; do not edit here.\n\n"
       + js("CATEGORIES", categories) + js("ITEMS", items) + js("BRANCHES", branches) + js("LEAGUES", leagues)
       + "export const byId = (id) => ITEMS.find((i) => i.id === id);\n"
       "export const inCategory = (cat) => ITEMS.filter((i) => i.cat === cat);\n"
       "export const branchById = (id) => BRANCHES.find((b) => b.id === id);\n")
(ROOT / "js" / "data.js").write_text(out, encoding="utf-8")
print(f"data.js: {len(categories)} categories, {len(items)} visible items "
      f"({len(raw['items']) - len(items)} hidden), {len(branches)} branches, {len(leagues)} leagues, "
      f"{(ROOT / 'js' / 'data.js').stat().st_size / 1024:.0f} KB")
missing = [i["id"] for i in items if not (ROOT / i["img"]).exists()]
print("missing images:", missing or "none")
