#!/usr/bin/env python3
"""Lift KAI's wordmark out of their own pattern tile and set it level.

kaicoffeeco.com ships its brand pattern as an SVG (assets/brand/pattern.svg): the
ampersand plus "<AI COFFEE", drawn on a slant. The letters are real vectors, so
this finds the angle at which they sit flattest (the smallest union height is
cap height) and writes js/wordmark.js with one group per letter, so the opening
screen can raise them one at a time and the bar can drop "COFFEE" when it needs
the room.

Paths that sit wholly inside another path's box are hairline duplicates in the
tile and are left out; the largest path is the ampersand and is left out too.

    python3 scripts/extract_wordmark.py
"""
import json
import pathlib
import re

from playwright.sync_api import sync_playwright

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "assets/brand/pattern.svg"
OUT = ROOT / "js/wordmark.js"
PREVIEW = ROOT / "scripts/shots/wordmark-preview.png"

JS = r"""
([paths, flip]) => {
  const NS = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(NS, "svg");
  svg.setAttribute("width", "2000"); svg.setAttribute("height", "2000");
  document.body.append(svg);
  const chain = (a) => `rotate(${a.toFixed(3)}) ${flip}`;
  const make = (d) => {
    const g = document.createElementNS(NS, "g");
    const p = document.createElementNS(NS, "path");
    p.setAttribute("d", d); g.append(p); svg.append(g); return { g, p };
  };
  const all = paths.map(make);
  const box = (g) => { const b = g.getBBox(); return [b.x, b.y, b.width, b.height]; };
  // raw boxes (angle 0) to find the ampersand and the hidden duplicates
  all.forEach(({ p }) => p.setAttribute("transform", chain(0)));
  const raw = all.map(({ g }) => box(g));
  const area = (b) => b[2] * b[3];
  const amp = raw.reduce((m, b, i) => (area(b) > area(raw[m]) ? i : m), 0);
  const inside = (a, b) => a[0] >= b[0] - 1e-6 && a[1] >= b[1] - 1e-6 &&
                          a[0] + a[2] <= b[0] + b[2] + 1e-6 && a[1] + a[3] <= b[1] + b[3] + 1e-6;
  const keep = raw.map((b, i) => i !== amp && !raw.some((o, j) => j !== i && j !== amp && area(o) > area(b) && inside(b, o)));
  const letters = all.filter((_, i) => keep[i]);
  const union = () => {
    let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    letters.forEach(({ g }) => { const [x, y, w, h] = box(g); x0 = Math.min(x0, x); y0 = Math.min(y0, y); x1 = Math.max(x1, x + w); y1 = Math.max(y1, y + h); });
    return [x0, y0, x1 - x0, y1 - y0];
  };
  let best = null;
  for (let a = 5; a <= 40; a += 0.01) {
    letters.forEach(({ p }) => p.setAttribute("transform", chain(a)));
    const u = union();
    if (!best || u[3] < best.h) best = { a, h: u[3] };
  }
  letters.forEach(({ p }) => p.setAttribute("transform", chain(best.a)));
  const u = union();
  const out = letters.map(({ g, p }) => ({ d: p.getAttribute("d"), t: p.getAttribute("transform"), b: box(g) }))
                     .sort((m, n) => m.b[0] - n.b[0]);
  return { angle: best.a, union: u, letters: out, dropped: raw.map((b, i) => (keep[i] ? null : i)).filter((i) => i !== null) };
}
"""


def main():
    svg = SRC.read_text(encoding="utf-8")
    flip = re.search(r'<g transform="([^"]+)">', svg).group(1)
    paths = re.findall(r'<path[^>]*?d="([^"]+)"', svg)
    with sync_playwright() as p:
        b = p.chromium.launch(channel="chrome", headless=True)
        pg = b.new_page()
        pg.set_content("<html><body></body></html>")
        res = pg.evaluate(JS, [paths, flip])
        b.close()

    letters = res["letters"]
    assert len(letters) == 9, f"expected 9 letters (<AI COFFEE), got {len(letters)}"
    x, y, w, h = res["union"]
    pad = h * 0.04
    vb = f"{x - pad:.3f} {y - pad:.3f} {w + 2 * pad:.3f} {h + 2 * pad:.3f}"
    glyph = lambda i, L: f'<g class="wl" style="--i:{i}"><path transform="{L["t"]}" d="{L["d"]}"/></g>'
    kai = "".join(glyph(i, L) for i, L in enumerate(letters[:3]))
    coffee = "".join(glyph(i + 3, L) for i, L in enumerate(letters[3:]))
    inner = f'<g class="wm-kai">{kai}</g><g class="wm-coffee">{coffee}</g>'
    OUT.write_text(
        "// Generated by scripts/extract_wordmark.py from assets/brand/pattern.svg —\n"
        "// KAI's own \"<AI COFFEE\" lettering, set level. Do not edit by hand.\n"
        f"export const WORDMARK_VIEWBOX = \"{vb}\";\n"
        f"export const WORDMARK_ASPECT = {(w + 2 * pad) / (h + 2 * pad):.4f};\n"
        f"export const WORDMARK_INNER = `{inner}`;\n"
        "export const WORDMARK = `<svg class=\"wm\" viewBox=\"${WORDMARK_VIEWBOX}\" fill=\"currentColor\" "
        "role=\"img\" aria-label=\"KAI Coffee\" focusable=\"false\">${WORDMARK_INNER}</svg>`;\n",
        encoding="utf-8")
    print(f"  angle {res['angle']:.2f}°, dropped paths {res['dropped']}, viewBox {vb}, aspect {(w + 2 * pad) / (h + 2 * pad):.2f}")
    print(f"  {OUT.relative_to(ROOT)}  {OUT.stat().st_size / 1024:.1f} KB")

    # a look at the result, big, in both inks
    PREVIEW.parent.mkdir(parents=True, exist_ok=True)
    html = (f'<html><body style="margin:0;background:#FCF7F1">'
            f'<div style="padding:40px;color:#17150F"><svg viewBox="{vb}" width="1100" fill="currentColor">{inner}</svg></div>'
            f'<div style="padding:40px;background:#100F0C;color:#F3EEE6"><svg viewBox="{vb}" width="1100" fill="currentColor">{inner}</svg></div>'
            f'</body></html>')
    with sync_playwright() as p:
        b = p.chromium.launch(channel="chrome", headless=True)
        pg = b.new_page(viewport={"width": 1180, "height": 600})
        pg.set_content(html); pg.wait_for_timeout(200)
        pg.screenshot(path=str(PREVIEW), full_page=True)
        b.close()


if __name__ == "__main__":
    main()
